### ISSUE TITLE
could not find `data` in `pcap_parser`

### ISSUE THREAD

**Issue by allengrant** [rusticata/pcap-parser#17]
Has there been a recent change to the pcap-parser API? I ran a minimal example and go the following import error.

```bash
   Compiling test-rust v0.1.0 (/Users/w/Dropbox/Codin/test-rust)
error[E0432]: unresolved import `pcap_parser::data`
 --> src/main.rs:1:18
  |
1 | use pcap_parser::data::{get_packetdata, PacketData};
  |                  ^^^^ could not find `data` in `pcap_parser`
```

To prove I'm not insane, I build a minimal project as follows:

Cargo.toml:

```toml
[package]
name = "test-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap-parser = "0.13.1"
```

main.rs:

```rust
use pcap_parser::data::{get_packetdata, PacketData};
use pcap_parser::pcapng::EnhancedPacketBlock;
use pcap_parser::Linktype;

fn parse_block_content<'a>(
    epb: &'a EnhancedPacketBlock<'_>,
    linktype: Linktype
) -> Option<()> {
    let packet_data =  get_packetdata(epb.data, linktype, epb.caplen as usize)?;
    match packet_data {
        PacketData::L3(_, _data) => {
            // ...
        },
        _ => println!("Unsupported link type"),
    }
    Some(())
}

fn main() {

}
```

The latter file is taken exactly from the docs.
